### PR TITLE
AutoStrategist which executes given strategies

### PR DESCRIPTION
**Pull request by Hecate2**

### CODE REVIEW

**Comment by Hecate2** [comment]
Extra test needed for reading environment variables on non-Windows operating systems (codes involving `EnvironmentVariableTarget.User`).  
(An environment variable `RUNNER_OS` is always set by default in github actions, but not utilized now)
Extra test needed for executing strategy in real environment (https://github.com/Hecate2/maintainer/blob/220d9c18622ea45151c192038c83a0d2712826d9/BurgerNeo.AutoStrategist/Program.cs#L103-L132).

**Comment by Hecate2** [comment]
Current version is not suitable for case where Agent(0)==null but Agent(1,2,3,...) has effective value. 
Only suitable for Agent(0,1, ..., i) is effective and Agent(i+1, i+2, ...) == null
Will make improvements in following commits

**Comment by Hecate2** [comment]
> 
> 
> Current version is not suitable for case where Agent(0)==null but Agent(1,2,3,...) has effective value. Only suitable for Agent(0,1, ..., i) is effective and Agent(i+1, i+2, ...) == null Will make improvements in following commits

Expected to have been fixed by the commit above

**Comment by Hecate2** [comment]
Logs are printed to the console about the execution steps

**Comment by Hecate2** [comment]
The two commits above need administrative revision

**Comment by Hecate2** [comment]
The commit above enables the maintainer to generate strategies by itself. No need to read given strategies from environement variables.

**Comment by vang1ong7ang** [comment]
auto strategy is impled in tee repo

**Pull request closed without merging**
